<script lang="ts">
    import { onMount } from 'svelte';
  
    import {
        getFingerprint, getFingerprintData,
        setOption as setFingerprintOption,
        includeComponent as includeFingerprintComponent,
    } from '@thumbmarkjs/thumbmarkjs'

    let fp = $state('');
    let fp_details = $state('');

    function screenSize() {
        return Promise.resolve({width: screen.width, height: screen.height});
    }

    function buildBrowserFingerprintKey(c: any) : string {
        let s = c.system.platform.split(' ')[0].toLowerCase();

        if (navigator.userAgent.match(/iPhone|iPad/i)) {
            s = 'ios';
        } else if (navigator.userAgent.includes('Android')) {
            s = 'android';
        }

        let k = [
            s,
            c.system.browser.name.toLowerCase(),
            `${c.size.width}x${c.size.height}`,
        ];
        if (c.screen.is_touchscreen) {
            k.push('touch');
        };
        return k.join('_');
    }

    async function generateBrowserFingerprint() {
        try {
            const c = await getFingerprintData();
            const h = await getFingerprint();
            fp_details = JSON.stringify(c, null, 2);
            fp_details = `${buildBrowserFingerprintKey(c)}_${h}`;
        } catch (error) {
            console.error('Error generating fingerprint:', error);
            // Re-throw the error so the caller can handle it
            throw error;
        }
    }

    onMount(() => {
        setFingerprintOption('logging', false);
        setFingerprintOption('exclude', ['webgl', 'canvas', 'permissions', 'audio.sampleHash']);
        includeFingerprintComponent('size', screenSize);
        generateBrowserFingerprint();
    });
</script>
<div>
    <h1>Browser Fingerprint</h1>
    <p><b>Info:</b> Client-Side browser-fingerprint generated by JavaScript</p>
    <p><b>Fingerprint:</b> {fp}</p>
    <h2>Details:</h2>
    <pre>
        {fp_details}
    </pre>
</div>
